---

- name: cuda-drivers in NVIDIA APT repository is removed
  apt:
    name: cuda-drivers
    state: absent
    autoremove: yes
    install_recommends: no
    update_cache: "{{ 'yes' if not ansible_check_mode | bool else 'no' }}"
  when: not ansible_check_mode and nvidia_driver_package_name != "cuda-drivers"

- name: graphics-driver ppa APT repository is registered
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    filename: graphics-driver
    state: present
    mode: 0644
    update_cache: "{{ 'yes' if not ansible_check_mode | bool else 'no' }}"
  when: nvidia_driver_repo == "ppa"

- name: NVIDIA graphics driver {{ nvidia_driver_package_name }} is installed
  apt:
    name: "{{ nvidia_driver_package_name }}={{ nvidia_driver_package_version }}"
    state: present
    install_recommends: no
    update_cache: "{{ 'yes' if not ansible_check_mode | bool else 'no' }}"
  when: not ansible_check_mode

- name: NVIDIA CUDA runtime library is installed
  apt:
    name: "libcuda1-{{ nvidia_driver_version_major }}={{ nvidia_driver_package_version }}"
    state: present
    install_recommends: no
    update_cache: "{{ 'yes' if not ansible_check_mode | bool else 'no' }}"
  when: not ansible_check_mode and nvidia_driver_package_name != "cuda-drivers"

- name: disable nonveau, opensource version of NVIDIA graphics driver
  lineinfile:
    dest: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT nouveau.modeset=0"'
    validate: 'sh -n %s'
    create: yes
